services:
  - type: web
    name: qadiya
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    autoDeployTrigger: checksPass
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    dockerContext: .
