import type { CaseDNA } from './dna.js';
import type { CaseTemplate } from './templates.js';

export const CURATED_CASE_DNAS: readonly CaseDNA[] = [
  {
    id: 'warehouse-access-misdirection',
    family: 'innocence',
    mode: 'standard',
    complexity: 2,
    truthPattern: 'wrongly-accused',
    primaryEvidenceKind: 'digital',
    secondaryEvidenceKinds: ['testimony'],
    witnessPattern: 'mistaken-but-sincere',
    modifiers: ['alternative-suspect'],
    minDefendants: 1,
    maxDefendants: 1,
    variableRoleBudget: { min: 1, max: 4 },
  },
];

export const CURATED_CASE_TEMPLATES: readonly CaseTemplate[] = [
  {
    id: 'warehouse-access-misdirection:v1',
    revision: 1,
    dnaId: 'warehouse-access-misdirection',
    supportedDefendantCounts: [1],
    characterSlots: [
      {
        id: 'defendant',
        publicNames: { values: ['سالم', 'ناصر', 'مازن', 'فهد'] },
        genders: { values: ['male'] },
        age: { min: 26, max: 42 },
        occupations: { values: ['موظف مخازن', 'مندوب مشتريات', 'مشرف عمليات'] },
        memoryProfiles: { values: ['normal', 'strong'] },
      },
      {
        id: 'witness',
        publicNames: { values: ['مريم', 'هند', 'نورة', 'ليان'] },
        genders: { values: ['female'] },
        age: { min: 24, max: 45 },
        occupations: { values: ['موظفة استقبال', 'محاسبة', 'موظفة أمن'] },
        memoryProfiles: { values: ['normal', 'uncertain'] },
      },
      {
        id: 'alternate-suspect',
        publicNames: { values: ['عمر', 'زياد', 'راشد'] },
        genders: { values: ['male'] },
        age: { min: 25, max: 44 },
        occupations: { values: ['فني صيانة', 'سائق توصيل', 'عامل مخزن'] },
        memoryProfiles: { values: ['normal'] },
      },
    ],
    defendantCharacterSlotIds: ['defendant'],
    locations: [
      { id: 'warehouse', label: 'المستودع' },
      { id: 'gate', label: 'بوابة المستودع' },
      { id: 'street', label: 'الشارع الرئيسي' },
    ],
    travelLinks: [
      { id: 'warehouse-gate', fromLocationId: 'warehouse', toLocationId: 'gate', minTravelMinutes: 2, bidirectional: true },
      { id: 'gate-street', fromLocationId: 'gate', toLocationId: 'street', minTravelMinutes: 4, bidirectional: true },
    ],
    facts: [
      {
        id: 'fact-defendant-near-gate',
        description: 'المتهم كان قرب بوابة المستودع قبل الواقعة.',
        subjectCharacterSlotId: 'defendant',
        predicate: 'was-near',
        objectRefId: 'gate',
      },
      {
        id: 'fact-defendant-left-before-entry',
        description: 'المتهم غادر المنطقة قبل الدخول غير المشروع.',
        subjectCharacterSlotId: 'defendant',
        predicate: 'left-before',
        objectRefId: 'warehouse',
      },
      {
        id: 'fact-alternate-used-credential',
        description: 'المشتبه البديل استخدم بيانات دخول مرتبطة بالمتهم.',
        subjectCharacterSlotId: 'alternate-suspect',
        predicate: 'used-credential-linked-to',
        objectRefId: 'defendant',
      },
      {
        id: 'fact-witness-saw-similar-build',
        description: 'الشاهدة رأت شخصًا ببنية مشابهة ولم تر الوجه بوضوح.',
        subjectCharacterSlotId: 'witness',
        predicate: 'observed-similar-build',
        objectRefId: 'alternate-suspect',
      },
    ],
    timeline: [
      {
        id: 'event-defendant-near-gate',
        startMinute: 540,
        endMinute: 543,
        locationId: 'gate',
        actorCharacterSlotIds: ['defendant'],
        factIds: ['fact-defendant-near-gate'],
      },
      {
        id: 'event-defendant-left',
        startMinute: 547,
        locationId: 'street',
        actorCharacterSlotIds: ['defendant'],
        factIds: ['fact-defendant-left-before-entry'],
      },
      {
        id: 'event-illegal-entry',
        startMinute: 552,
        locationId: 'warehouse',
        actorCharacterSlotIds: ['alternate-suspect'],
        factIds: ['fact-alternate-used-credential', 'fact-witness-saw-similar-build'],
      },
    ],
    knowledge: [
      {
        id: 'knowledge-witness-build',
        holderCharacterSlotId: 'witness',
        factId: 'fact-witness-saw-similar-build',
        perceivedDescription: 'رأيت شخصًا ببنية تشبه المتهم، وأظن أنه كان هو رغم أنني لم أر الوجه بوضوح.',
        source: {
          kind: 'direct-observation',
          sourceTimelineEventId: 'event-illegal-entry',
          precisionLimit: 'approximate',
        },
        accuracy: 0.72,
        confidence: 0.9,
        precision: 'approximate',
        belief: 'believes-true',
      },
      {
        id: 'knowledge-defendant-left',
        holderCharacterSlotId: 'defendant',
        factId: 'fact-defendant-left-before-entry',
        perceivedDescription: 'أتذكر أنني غادرت المنطقة ووصلت إلى الشارع قبل وقت الدخول إلى المستودع.',
        source: {
          kind: 'self-memory',
          sourceTimelineEventId: 'event-defendant-left',
          precisionLimit: 'narrow-range',
        },
        accuracy: 0.98,
        confidence: 0.95,
        precision: 'narrow-range',
        belief: 'believes-true',
      },
    ],
    evidence: [
      {
        id: 'evidence-gate-log',
        title: 'سجل الدخول الإلكتروني',
        factIds: ['fact-alternate-used-credential'],
        provenance: {
          kind: 'digital',
          sourceTimelineEventId: 'event-illegal-entry',
          description: 'السجل يثبت استخدام بيانات دخول مرتبطة بالمتهم، لكنه لا يثبت هوية المستخدم.',
        },
        reliability: 0.94,
        ambiguity: 0.64,
        discoverableByRoleIds: ['prosecution', 'defense'],
      },
      {
        id: 'evidence-witness-account',
        title: 'إفادة الشاهدة',
        factIds: ['fact-witness-saw-similar-build'],
        provenance: {
          kind: 'testimony',
          sourceCharacterSlotId: 'witness',
          sourceTimelineEventId: 'event-illegal-entry',
          description: 'رؤية جزئية لشخص ببنية مشابهة قرب وقت الواقعة.',
        },
        reliability: 0.66,
        ambiguity: 0.72,
        discoverableByRoleIds: ['prosecution', 'defense'],
      },
    ],
    roles: [
      {
        id: 'role-witness',
        roleKind: 'witness',
        characterSlotId: 'witness',
        required: true,
        replaceable: false,
        canBecomeSystemCharacter: true,
        canBecomeDocument: false,
        critical: false,
        engagement: {
          exclusiveInformation: 0.8,
          meaningfulDecisions: 0.55,
          concealmentPressure: 0.15,
          influencePotential: 0.8,
          personalRisk: 0.2,
        },
      },
      {
        id: 'role-alternate-suspect',
        roleKind: 'secondary-suspect',
        characterSlotId: 'alternate-suspect',
        required: false,
        replaceable: true,
        canBecomeSystemCharacter: true,
        canBecomeDocument: false,
        critical: false,
        engagement: {
          exclusiveInformation: 0.9,
          meaningfulDecisions: 0.7,
          concealmentPressure: 0.9,
          influencePotential: 0.65,
          personalRisk: 0.85,
        },
      },
    ],
    charges: [
      {
        id: 'charge-unlawful-entry',
        title: 'دخول غير مشروع',
        defendantCharacterSlotIds: ['defendant'],
        burden: 'beyond-reasonable-doubt',
        elements: [
          {
            id: 'charge-unlawful-entry:entry',
            title: 'أن يكون المتهم هو من دخل الموقع',
            truth: 'not-satisfied',
            basisFactIds: ['fact-defendant-left-before-entry', 'fact-alternate-used-credential'],
          },
        ],
      },
    ],
  },
];
